name: Cleanup workflow and docker images

# on:
#   schedule:
#     # Run task once a week
#     - cron: '0 0 * * 0'

on:
  workflow_call:
    secrets:
      READ_AND_DELETE_PACKAGES_TOKEN:
        required: true
    inputs:
      imageName:
        required: false
        default: ''
        type: string
        description: Name of the image to delete, needs a slash at the beginning
      accountIsOrganisation:
        required: false
        default: true
        type: boolean
        description: Account type is organisation, default to true
      keepAtLeast:
        required: false
        default: 6
        type: number
        description: Keep at least this many images
      cutOff:
        required: false
        default: 'One week ago UTC'
        type: string
        description: Cut off images older than this

jobs:
  deleteOldPackages:
    name: Delete old packages
    runs-on: ubuntu-latest
    steps:
      - name: Lowercase repository name
        uses: ASzc/change-string-case-action@v4
        id: repository_name
        with:
          string: ${{ github.repository }}
      - name: Lowercase repository owner
        uses: ASzc/change-string-case-action@v4
        id: repository_owner
        with:
          string: ${{ github.repository_owner }}
      - name: Plain repository name
        uses: mad9000/actions-find-and-replace-string@2
        id: plain_repository_name
        with:
          source: ${{ steps.repository_name.outputs.lowercase }}
          find: ${{ steps.repository_owner.outputs.lowercase }}/
          replace: ''
      - name: Delete containers
        if: ${{ inputs.accountIsOrganisation == false }}
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ steps.plain_repository_name.outputs.value }}${{ inputs.imageName }}
          cut-off: ${{ inputs.cutOff }}
          timestamp-to-use: updated_at
          account-type: personal
          keep-at-least: ${{ inputs.keepAtLeast }}
          skip-tags: latest
          token: ${{ secrets.READ_AND_DELETE_PACKAGES_TOKEN }}
      - name: Delete containers
        if: ${{ inputs.accountIsOrganisation == true }}
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ steps.plain_repository_name.outputs.value }}${{ inputs.imageName }}
          cut-off: ${{ inputs.cutOff }}
          timestamp-to-use: updated_at
          account-type: org
          org-name: ${{ steps.repository_owner.outputs.lowercase }}
          keep-at-least: ${{ inputs.keepAtLeast }}
          skip-tags: latest
          token: ${{ secrets.READ_AND_DELETE_PACKAGES_TOKEN }}
